# Found this cool Black format workflow

# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, Black is run and its changes are committed back to the incoming pull request.
# https://github.com/cclauss/autoblack

name: autoblack
on:
  push:
    branches:  [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Black
        run: pip install black
      - name: Run black .
        run: black .
      - name: Commit black changes to the pull request
        run: |
          git config --global user.name 'autoblack'
          git config --global user.email 'itsjustmustafa@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit --allow-empty -am "fixup: Format Python code with Black"
          git pull --ff
          git push
