# This workflow will format using Black

name: Python application

on:
  push:
    branches:  [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
