# Found this cool Black format workflow

# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, Black is run and its changes are committed back to the incoming pull request.
# https://github.com/cclauss/autoblack

name: make_docs
on:
  push:
    branches:  [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: Sphinx-docs/
    steps:
      - name: Make markdown docs
        run: |
          cd Sphinx-docs
          make markdown
          cd ..
        working-directory: ${{env.working-directory}}
          
